version: '3.8'

services:
  node:
    container_name: '${PROJECT_NAME}-node'
    image: '${NODE_DOCKER_TAG:-node:14}'
    working_dir: /var/www/app
    user: '${UID:-1000}:${GID:-1000}'
    ports:
      - ${NODE_DEVSERVER_PORT:-8080}:8080
    environment:
      - YARN_CACHE_FOLDER=/home/node/.yarn
      - RUNNING_IN_DOCKER=true
    volumes:
      - ${APP_DIR:-../}:/var/www/app
      - ./node/yarn:/home/node/.yarn
      - ./node/npm:/home/node/.npm
      - ~/.gitconfig:/home/node/.gitconfig
      - ~/.ssh:/home/node/.ssh
    networks:
      - docker_vue_net
    profiles:
      - tools

  yarn-devserver:
    container_name: '${PROJECT_NAME}-yarn-devserver'
    image: '${NODE_DOCKER_TAG:-node:14}'
    working_dir: /var/www/app
    user: '${UID:-1000}:${GID:-1000}'
    command: yarn saber
    environment:
      - YARN_CACHE_FOLDER=/home/node/.yarn
      - RUNNING_IN_DOCKER=true
    ports:
      - ${NODE_DEVSERVER_PORT:-8080}:3000
    volumes:
      - ${APP_DIR:-../}:/var/www/app
      - ./node/yarn:/home/node/.yarn
      - ./node/npm:/home/node/.npm
    networks:
      - docker_vue_net
    profiles:
      - web

networks:
  docker_vue_net:
